apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-pod-offload-deployment
  labels:
    app: random-pod-offload-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-pod-offload-deployment
  template:
    metadata:
      labels:
        app: random-pod-offload-deployment
    spec:
      containers:
      - name: random-pod-offload-deployment
        image: registry.cn-qingdao.aliyuncs.com/qiaoyufei01/random-pod-offload-deployment:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: random-pod-offload-deployment
          mountPath: /home/service/random
        resources:
          limits:
            memory: 1Gi
            ephemeral-storage: 2Gi
          requests:
            memory: 1Gi
            ephemeral-storage: 2Gi
        ports:
        - name: http
          containerPort: 4001
      volumes:
      - name: random-pod-offload-deployment-storage
        hostPath:
          path: /home/cloudmaster/cloudHTTP/cloud/app/random-pod-offload-deployment/mapping
   


