apiVersion: apps/v1
kind: Deployment
metadata:
#  记得根据node修改名字
  name: node-resource-deployment
  labels:
    app: node-resource-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-resource-deployment
  template:
    metadata:
      labels:
        app: node-resource-deployment
    spec:
      containers:
      - name: node-resource-deployment
        image: registry.cn-qingdao.aliyuncs.com/qiaoyufei01/node-resource:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 1Gi
            ephemeral-storage: 2Gi
          requests:
            memory: 1Gi
            ephemeral-storage: 2Gi
        ports:
        - name: http
          containerPort: 7000
   


